export { default as initBlocks } from './BlocksManager'
export { default as initNav } from './Nav'
export { default as initWallet } from './Wallet'
export { default as volume } from './Settings/volume'
export { default as rumble } from './Settings/rumble'
export { default as watchColorSchemes } from './ColorSchemes'
