# https://github.com/lycheeverse/lychee-action/

name: Links validity (on pull request)

on:
  pull_request:
    branches: [ main ]

jobs:

  linkChecker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: './**/*.html'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
